-- HHT Commerce Agent baseline schema.
-- This migration creates the schema required by the current production code.
-- It is intentionally idempotent so it can run against a fresh or existing project.
BEGIN;

CREATE TABLE IF NOT EXISTS public.listings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id text NOT NULL DEFAULT '',
    offer_id text NOT NULL DEFAULT '',
    sku text NOT NULL,
    marketplace text NOT NULL DEFAULT 'EBAY_US',
    data_json text NOT NULL,
    source_updated_at text,
    imported_at text NOT NULL,
    lifecycle_status text NOT NULL DEFAULT 'active',
    listing_start_time text,
    quantity_sold integer NOT NULL DEFAULT 0,
    watch_count integer,
    ownership_classification text NOT NULL DEFAULT 'unknown',
    UNIQUE (sku, marketplace)
);

CREATE TABLE IF NOT EXISTS public.recommendations (
    id text PRIMARY KEY,
    listing_row_id bigint NOT NULL REFERENCES public.listings(id),
    current_json text NOT NULL,
    proposed_json text NOT NULL,
    findings_json text NOT NULL,
    score integer NOT NULL,
    classification text NOT NULL,
    reason text NOT NULL,
    confidence text NOT NULL,
    risk text NOT NULL,
    status text NOT NULL DEFAULT 'Pending',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version_number integer NOT NULL DEFAULT 1,
    is_current boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.actions (
    id text PRIMARY KEY,
    recommendation_id text NOT NULL REFERENCES public.recommendations(id),
    listing_row_id bigint NOT NULL REFERENCES public.listings(id),
    approved_json text NOT NULL,
    old_json text NOT NULL,
    new_json text NOT NULL DEFAULT '{}',
    status text NOT NULL DEFAULT 'Approved',
    ebay_result_json text NOT NULL DEFAULT '{}',
    error text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    applied_at text,
    recommendation_version integer NOT NULL DEFAULT 1,
    listing_snapshot_json text NOT NULL DEFAULT '{}',
    listing_state_hash text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.settings (
    id integer PRIMARY KEY CHECK (id = 1),
    mode text NOT NULL DEFAULT 'recommend',
    max_price_reduction_pct double precision NOT NULL DEFAULT 10,
    minimum_price double precision NOT NULL DEFAULT 0,
    minimum_profit double precision NOT NULL DEFAULT 0,
    high_value_threshold double precision NOT NULL DEFAULT 250,
    require_vintage integer NOT NULL DEFAULT 1,
    require_designer integer NOT NULL DEFAULT 1,
    require_collectible integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.commerce_jobs (
    id text PRIMARY KEY,
    kind text NOT NULL,
    status text NOT NULL,
    progress integer NOT NULL DEFAULT 0,
    result_json text NOT NULL DEFAULT '{}',
    error text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.enrichment_checkpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_row_id bigint NOT NULL UNIQUE REFERENCES public.listings(id),
    listing_id text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    enriched_at text,
    last_error text NOT NULL DEFAULT '',
    details_json text NOT NULL DEFAULT '{}',
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.listing_performance_daily (
    id text PRIMARY KEY,
    listing_row_id bigint REFERENCES public.listings(id),
    ebay_listing_id text NOT NULL,
    metric_date text NOT NULL,
    snapshot_kind text NOT NULL DEFAULT 'rolling_listing_snapshot',
    impressions integer,
    search_impressions integer,
    views integer,
    ctr double precision,
    conversion_rate double precision,
    transactions integer,
    watch_count integer,
    source text NOT NULL DEFAULT 'ebay_analytics',
    metric_provenance text NOT NULL DEFAULT 'official_ebay_metric',
    raw_json text NOT NULL DEFAULT '{}',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE (ebay_listing_id, metric_date)
);

CREATE TABLE IF NOT EXISTS public.listing_versions (
    id text PRIMARY KEY,
    listing_row_id bigint NOT NULL REFERENCES public.listings(id),
    version_number integer NOT NULL,
    source text NOT NULL,
    state_json text NOT NULL,
    evidence_json text NOT NULL DEFAULT '{}',
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fulfillment_orders (
    order_id text PRIMARY KEY,
    created_at text,
    total_value double precision NOT NULL DEFAULT 0,
    line_items_json text NOT NULL DEFAULT '[]',
    raw_json text NOT NULL DEFAULT '{}',
    synced_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rotation_actions (
    id text PRIMARY KEY,
    ebay_listing_id text NOT NULL,
    action text NOT NULL,
    evidence_json text NOT NULL,
    status text NOT NULL DEFAULT 'Pending',
    created_at text NOT NULL,
    approved_at text
);

INSERT INTO public.settings(id) VALUES (1) ON CONFLICT (id) DO NOTHING;
CREATE INDEX IF NOT EXISTS enrichment_checkpoints_status_idx ON public.enrichment_checkpoints(status, updated_at);
CREATE INDEX IF NOT EXISTS listing_performance_daily_date_idx ON public.listing_performance_daily(metric_date, ebay_listing_id);

COMMIT;
