name: Main Config
version: 1.0.0
schema: v1
envFile: ".env"

models:
  - provider: groq
    name: llava-next-34b
    roles:
      - chat
      - edit
    apiKey: $GROQ_API_KEY

  - provider: groq
    name: mixtral-8x7b
    roles:
      - chat
      - edit
      - autocomplete
    apiKey: $GROQ_API_KEY

  - provider: groq
    name: gemma-7b-it
    roles:
      - chat
      - edit
    apiKey: $GROQ_API_KEY

tabAutocompleteModel:
  provider: groq
  name: mixtral-8x7b
  apiKey: $GROQ_API_KEY
